# Generated by Django 4.2 on 2023-04-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='domicio',
            new_name='domicilio',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
